# Welcome to Jekyll!

# Website settings
title: "Prateek"
description: "Prateek's blog,use Jekyll and github pages."
keywords: "Prateek,Khurana,prateekk91,Jekyll,github,gh-pages"
baseurl: "/"
url: "http://www.jack003.com"
# url: "http://127.0.0.1:4000"

# author
author:
  name: 'Prateek Khurana'
  first_name: 'Prateek'
  last_name: 'Khurana'
  email: 'pkhurana@eng.ucsd.edu'
  facebook_username: 'prateekkhurana91'
  linkedin_username: 'prateekk91'
  github_username: 'prateekk91'
  head_img: 'static/img/landing/Prateek.jpg'
  desc: 'I am a Software Developer who is currently pursuing his Masters in Computer Science at the University of California San Diego. I have experience building applications for mobile, desktop and the web, and am skilled in C/C++, Java and Android development.'

# sections
sections:
  - id: 'about-me'
    i18n: 'nav.about_me'
    name: 'About'
    tpl: 'about.html'
    css: ''

  - id: 'career'
    i18n: 'nav.career'
    name: 'Career'
    tpl: 'career.html'
    css: 'timeline'

  - id: 'skills'
    i18n: 'nav.skills'
    name: 'Skills'
    tpl: 'skills.html'
    css: 'team'

  - id: 'projects'
    i18n: 'nav.projects'
    name: 'Projects'
    tpl: 'projects.html'
    css: 'project'

  - id: 'blog'
    i18n: 'nav.blog'
    name: 'Publication'
    tpl: 'blog.html'
    css: 'testimonials navy-section'


# localization
languages:
  - locale: 'en'
    flag: 'static/img/flags/United-States.png'

# blog img path
img_path: 'http://www.jack003.com/static/img/blog'

# donate
donate:
  wechat1: 'static/img/pay/w1.jpeg'
  wechat5: 'static/img/pay/w5.jpeg'

# comment
changyan:
  # appid: cysfY7ULn
  # conf: prod_861928934cecb7a18e15bedaed9dae29
disqus:
  name: jalpc
  public_key: tj2MPaNlHMONwTH5bGDNSXyaBpW7q282MeUzh5CwcjJerNhK8Kxk3aWo7IckzTX7

# share
bshare:
  uuid: 513f778e-a8f7-4c20-9ec2-d29cc2328d75

# baidu analytics
ba:
  # uuid: 317acca9ef9255b934e46371e471431d

# google analytics
ga:
  id: UA-73784599-1

# growingIO
gio:
  id: a49d4901c7853da9

# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
